import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import { SpeedInsights } from "@vercel/speed-insights/next";
import { Analytics } from "@vercel/analytics/react";
import Header from "@/components/header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "RustiQ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  data,
}: Readonly<{
  children: React.ReactNode;
  data: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <div>{data}</div>
        {children}
        <SpeedInsights />
        <Analytics />
      </body>
    </html>
  );
}
