import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import { SpeedInsights } from "@vercel/speed-insights/next";
import { Analytics } from "@vercel/analytics/react";
import Header from "@/components/header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "RustiQ",
  description: "Generated by create next app",
  icons: {
    icon: [
      { url: "/logo/favicon-16x16.png", sizes: "16x16" },
      { url: "/logo/favicon-32x32.png", sizes: "32x32" },
    ],
    shortcut: "/logo/favicon.ico",
    apple: "/logo/apple-touch-icon.png",
  },
};

export default function RootLayout({
  children,
  data,
}: Readonly<{
  children: React.ReactNode;
  data: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className + "flex h-screen"}>
        <Header />
        <div>{data}</div>
        {children}
        <SpeedInsights />
        <Analytics />
      </body>
    </html>
  );
}
